version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: threed_generator
    ports:
      - "5432:5432"
    volumes:
      - ./database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - postgres_data:/var/lib/postgresql/data


  worker:
    build: 
      context: ./functions
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=db
      - LLM_URL=https://llm-api.alreadyagents.com/v1
      - LLM_MODEL=Llama-3.1-8B-Instruct
      - FUSION_URL=http://host.docker.internal:5000
      - EXPORT_DIR_HOST=/Users/robwells/sc/3d-model-generator/temp
    volumes:
      - ./temp:/temp
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db

  api:
    build:
      context: ./backend/ThreeDGenerator.Api
    ports:
      - "5045:5045"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=threed_generator;Username=admin;Password=password
    volumes:
      - ./temp:/app/temp
      - ./backend/ThreeDGenerator.Api:/app
    depends_on:
      - db
      
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api

volumes:
  postgres_data:
